# PC algorithms
pc_tetrad_05:
    algorithm_name: pc_tetrad
    test_name: conditional_gaussian_test
    test_params:
        alpha: 0.05
    bootstrap_strategy: bootstrap_2_100

# FGES algorithms (score-based)
fges_tetrad_pd2:
    algorithm_name: fges_tetrad
    score_name: conditional_gaussian_score
    score_params:
        penalty_discount: 2
    bootstrap_strategy: bootstrap_100_100

# BOSS algorithms (score-based)
boss_tetrad_pd2:
    algorithm_name: boss_tetrad
    score_name: conditional_gaussian_score
    score_params:
        penalty_discount: 2
    bootstrap_strategy: bootstrap_100_100

# GRASP configurations with alpha = 0.05

grasp_tetrad_pd2:
    algorithm_name: grasp_tetrad
    test_name: conditional_gaussian_test
    test_params:
        alpha: 0.05
    score_name: conditional_gaussian_score
    score_params:
        penalty_discount: 2
    bootstrap_strategy: bootstrap_100_100

# Direct-LiNGAM algorithms with varying penalty discount
directlingam_pd2:
    algorithm_name: directlingam_tetrad
    score_name: conditional_gaussian_score
    score_params:
        penalty_discount: 2
    bootstrap_strategy: bootstrap_100_100

# DAGMA algorithms (varying penalty_discount instead of lambda)
dagma_tetrad_pd2:
    algorithm_name: dagma_tetrad
    score_name: conditional_gaussian_score
    score_params:
        penalty_discount: 2
    bootstrap_strategy: bootstrap_2_100
